const INTERNAL_SERVER_ERROR = "服务器内部发生错误。"
const INCORRECT_REQUEST_PARAMETERS = "请求参数有误。"
const DATABASE_ERROR = "插入数据库失败。"
const UNAUTHORIZED = "无效的token。"
const FORBIDDEN = "无权限。"

const USER_ALREADY_EXISTS = "用户已存在。"
const USER_DOSE_NOT_EXIST = "用户不存在。"
const INCORRECT_USERNAME_OR_PASSWORD = "用户名或密码错误。"

module.exports = {
  INTERNAL_SERVER_ERROR,
  INCORRECT_REQUEST_PARAMETERS,
  DATABASE_ERROR,
  UNAUTHORIZED,
  FORBIDDEN,
  USER_ALREADY_EXISTS,
  USER_DOSE_NOT_EXIST,
  INCORRECT_USERNAME_OR_PASSWORD
}